### ISSUE TITLE
Install by prefix broken with cmake --install

### ISSUE THREAD

**Issue by gaspacio** [snitch-org/snitch#196] opened 2024-11-28 13:45 UTC
Hi! Reporting an issue with the Snitch install behavior with cmake ('main' branch).
Basically, specifying the install prefix with the configuration step will make it work. But specifying it directly along the 'cmake --install [build dir] --prefix [install prefix]' will retain the default install path.
 
These command will lead to a correct install:
 
```
cmake \
	-G Ninja \
	-DCMAKE_BUILD_TYPE="Release" \
	-DCMAKE_EXPORT_COMPILE_COMMANDS=1  --toolchain /opt/share/toolchain-configs/x86_64-multilib-linux-gnu.cmake \
	-DSNITCH_DO_TEST=ON \
	-DCMAKE_INSTALL_PREFIX=/home/user/workdir/install \
	-DSNITCH_ENABLE=ON \
	-S . -B build && \
cmake --build build --target all   && \
cmake --build build --target install
```

This won't work as intended:
 
```
cmake \
	-G Ninja \
	-DCMAKE_BUILD_TYPE="Release" \
	-DCMAKE_EXPORT_COMPILE_COMMANDS=1  --toolchain /opt/share/toolchain-configs/x86_64-multilib-linux-gnu.cmake \
	-DSNITCH_DO_TEST=ON \
	-S . -B build && \
cmake --build build --target all   && \
cmake --install build --prefix install
```

The error emerged when using a non-privileged OS user (Ubuntu 22:04) as this leads to install fail:
 
```
[53/53] Linking CXX executable tests/snitch_runtime_tests
-- Install configuration: "Release"
CMake Error at build/cmake_install.cmake:54 (file):
  file cannot create directory: /usr/local/include/snitch.  Maybe need
  administrative privileges.
```

I've noticed that calls to 'install()' are always using the 'DESTINATION ${CMAKE_INSTALL_PREFIX}/' prefix. By removing it, the behavior is once again as intended.
 
Would you consider this a bug or is it by design?

**Comment by cschreib** [comment] 2024-11-30 09:50
Hi and thanks for reporting this. This is the first time I hear about `cmake --install [...] --prefix [...]`! I always set this up at configure time. So no, this is not by design, it's a bug. I'll create a PR for this, thanks for the hint on the fix (it would have taken me a while to figure it out, the CMake documentation being what it is).

**Comment by cschreib** [comment] 2024-11-30 09:56
Should be fixed in https://github.com/snitch-org/snitch/pull/197.

**Closed** 2024-11-30 09:57 UTC
Labels: bug:confirmed

**Comment by gaspacio** [comment] 2024-12-01 14:38
Thank you!
