### ISSUE TITLE
Two different errors when REQUIRE_THROWS_AS doesn't throw

### ISSUE THREAD

**Issue by vid512** [snitch-org/snitch#143] opened 2023-11-28 17:28 UTC
This code:
```
#define SNITCH_IMPLEMENTATION
#include "snitch_all.hpp"

#include <exception>

void func() {}

TEST_CASE("blah") {
	REQUIRE_THROWS_AS(func(), std::runtime_error);
}
```
outputs:
```
starting a with snitch v1.2.3.f605e7e
==========================================
failed: running test case "blah"
          at a.cpp:14
          std::runtime_error expected but no exception thrown
failed: running test case "blah"
          at a.cpp:14
          std::runtime_error expected but other unknown exception thrown
==========================================
error: all tests failed (1 out of 1 test cases, 2 assertions, 1.976000e-04 seconds)
```

**Comment by cschreib** [comment] 2023-11-28 18:26
Huho, looks like a bug. I'll take a look.

**Comment by cschreib** [comment] 2023-11-28 20:05
Confirmed. A PR with a fix is in progress.

**Closed** 2023-11-28 20:21 UTC
Labels: bug:confirmed

**Comment by cschreib** [comment] 2023-11-28 20:23
This is fixed on the latest main branch. Please feel free to reopen if you still experience a problem with this.
