### ISSUE TITLE
Unexpected build errors with SNITCH_DO_TEST enabled and SNITCH_WITH_ALL_REPORTERS disabled

### ISSUE THREAD

**Issue by NicoMuleo** [snitch-org/snitch#190] opened 2024-10-31 14:04 UTC
When configuring Snitch with tests but not reporters as follows, for example:

```bash
cmake -S . -B /tmp/snitch/build -DSNITCH_DO_TEST=ON -DSNITCH_WITH_ALL_REPORTERS=OFF
```

and then building

```bash
cmake --build /tmp/snitch/build
```

The build fails with the error messages shown at the bottom. However, the problem does not occur when
disabling the reportes by setting both the SNITCH_WITH_CATCH2_XML_REPORTER and SNITCH_WITH_TEAMCITY_REPORTER flags.

```plaintext
$ cmake --build /tmp/snitch/build 

<...>

/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp: In function ‘void DOCTEST_ANON_FUNC_2()’:
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:21:37: error: ‘catch2_xml’ is not a member of ‘snitch::reporter’
   21 |     std::optional<snitch::reporter::catch2_xml::reporter> reporter;
      |                                     ^~~~~~~~~~
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:21:57: error: template argument 1 is invalid
   21 |     std::optional<snitch::reporter::catch2_xml::reporter> reporter;
      |                                                         ^
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp: In lambda function:
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:22:58: error: request for member ‘emplace’ in ‘reporter’, which is of non-class type ‘int’
   22 |     auto init      = [&](snitch::registry& r) { reporter.emplace(r); };
      |                                                          ^~~~~~~
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp: In lambda function:
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:24:25: error: request for member ‘value’ in ‘reporter’, which is of non-class type ‘int’
   24 |         return reporter.value().configure(r, k, v);
      |                         ^~~~~
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp: In lambda function:
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:27:25: error: request for member ‘value’ in ‘reporter’, which is of non-class type ‘int’
   27 |         return reporter.value().report(r, e);
      |                         ^~~~~
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp: In lambda function:
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:29:62: error: request for member ‘reset’ in ‘reporter’, which is of non-class type ‘int’
   29 |     auto finish = [&](snitch::registry&) noexcept { reporter.reset(); };
      |                                                              ^~~~~
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp: In function ‘void DOCTEST_ANON_FUNC_2()’:
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:31:36: error: no matching function for call to ‘snitch::registry::add_reporter(const char [4], DOCTEST_ANON_FUNC_2()::<lambda(snitch::registry&)>&, DOCTEST_ANON_FUNC_2()::<lambda(snitch::registry&, std::string_view, std::string_view)>&, DOCTEST_ANON_FUNC_2()::<lambda(const snitch::registry&, const data&)>&, DOCTEST_ANON_FUNC_2()::<lambda(snitch::registry&)>&)’
   31 |     framework.registry.add_reporter("xml", init, configure, report, finish);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user/Projects/snitch/include/snitch/snitch_macros_check_base.hpp:6,
                 from /home/user/Projects/snitch/include/snitch/snitch_macros_check.hpp:6,
                 from /home/user/Projects/snitch/include/snitch/snitch.hpp:16,
                 from /home/user/Projects/snitch/tests/testing.hpp:16,
                 from /home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:1:
/home/user/Projects/snitch/include/snitch/snitch_registry.hpp:211:22: note: candidate: ‘template<class T>  requires  reporter_type<T> std::string_view snitch::registry::add_reporter(std::string_view)’
  211 |     std::string_view add_reporter(std::string_view name) {
      |                      ^~~~~~~~~~~~
/home/user/Projects/snitch/include/snitch/snitch_registry.hpp:211:22: note:   template argument deduction/substitution failed:
/home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:31:36: note:   candidate expects 1 argument, 5 provided
   31 |     framework.registry.add_reporter("xml", init, configure, report, finish);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user/Projects/snitch/include/snitch/snitch_macros_check_base.hpp:6,
                 from /home/user/Projects/snitch/include/snitch/snitch_macros_check.hpp:6,
                 from /home/user/Projects/snitch/include/snitch/snitch.hpp:16,
                 from /home/user/Projects/snitch/tests/testing.hpp:16,
                 from /home/user/Projects/snitch/tests/approval_tests/reporter_catch2_xml.cpp:1:
/home/user/Projects/snitch/include/snitch/snitch_registry.hpp:202:36: note: candidate: ‘std::string_view snitch::registry::add_reporter(std::string_view, const std::optional<snitch::function_ref<void(snitch::registry&) noexcept> >&, const std::optional<snitch::function_ref<bool(snitch::registry&, std::basic_string_view<char>, std::basic_string_view<char>) noexcept> >&, const report_function&, const std::optional<snitch::function_ref<void(snitch::registry&) noexcept> >&)’
  202 |     SNITCH_EXPORT std::string_view add_reporter(
      |                                    ^~~~~~~~~~~~
/home/user/Projects/snitch/include/snitch/snitch_registry.hpp:205:58: note:   no known conversion for argument 3 from ‘DOCTEST_ANON_FUNC_2()::<lambda(snitch::registry&, std::string_view, std::string_view)>’ to ‘const std::optional<snitch::function_ref<bool(snitch::registry&, std::basic_string_view<char>, std::basic_string_view<char>) noexcept> >&’
  205 |         const std::optional<configure_report_function>&  configure,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
gmake[2]: *** [tests/CMakeFiles/snitch_approval_tests.dir/build.make:118: tests/CMakeFiles/snitch_approval_tests.dir/approval_tests/reporter_catch2_xml.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:232: tests/CMakeFiles/snitch_approval_tests.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

```

**Comment by cschreib** [comment] 2024-11-01 14:28
Thanks for catching this. Definitely a bug, i'll push a fix soon (currently traveling). 

The fact that this works when using `SNITCH_WITH_CATCH2_XML_REPORTER=OFF` and `SNITCH_WITH_TEAMCITY_REPORTER=OFF` is because `SNITCH_WITH_ALL_REPORTERS` is `ON` by default, and that takes precedence. To disable a reporter, both `SNITCH_WITH_ALL_REPORTERS` and `SNITCH_WITH_***_REPORTER` (replacing `***` with the name of the reporter) must be set to `OFF`. That bit at least is working as intended.

**Comment by cschreib** [comment] 2024-11-03 12:52
Should be fixed now, thanks!

**Closed** 2024-11-03 12:52 UTC
Labels: bug:confirmed

**Comment by NicoMuleo** [comment] 2024-11-04 09:25
Thank you very much!
